datadog:
  # kubelet configuration
  kubelet:
    # Toggle kubelet TLS verification
    # This is needed when installing on Docker-Desktop kubernetes environment
    tlsVerify: false

  # Prevents log spam: https://github.com/DataDog/helm-charts/issues/415
  kubeStateMetricsEnabled: false # Avoid deploying kube-state-metrics chart
  kubeStateMetricsCore:
    # Enable the kubernetes_state_core check in the Cluster Agent (Requires Cluster Agent 1.12.0+)
    enabled: true

  # Enable log Collection
  logs:
    enabled: true
    containerCollectAll: true

  # Set logging verbosity, valid log levels are: trace, debug, info, warn, error, critical, off
  logLevel: DEBUG

